LiveChat/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('account.urls', namespace='account')),
    path('', include('chat.urls', namespace='chat')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .forms import LoginForm

app_name = 'account'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html', form_class=LoginForm), name='login')
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create_room'),
    path('chat-admin/delete-room/<str:uuid>/', views.delete_room, name='delete_room'),
    path('chat-admin/', views.admin_room, name='admin_room'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/<str:uuid>/', views.room_view, name='room'),
    path('chat-admin/users/<uuid:uuid>/', views.user_view, name='user_detail'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

account/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLES_CHOICES = (
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=AGENT)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

chat/models.py
from django.db import models
from account.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f'{self.body}'


class Room(models.Model):
    class Status(models.TextChoices):
        WAITING = 'WAITING'
        ACTIVE = 'ACTIVE'
        CLOSED = 'CLOSED'

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.client}-{self.uuid}'

main/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from .models import User


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password',)


class AddUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'role', 'password',)
        widgets = {
            'email': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'name': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'role': forms.Select(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'password': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border',
                'type': 'password'
            })
        }


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'role',)
        widgets = {
            'email': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'name': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'role': forms.Select(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

account/views.py
from django.shortcuts import render

# Create your views here.

chat/views.py
import json
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from account.models import User
from .models import Room
from account.forms import AddUserForm


@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')
    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'Room created'})


@login_required
def delete_room(request, uuid):
    try:
        room = Room.objects.get(uuid=uuid)
        room.messages.all().delete()
        room.delete()
    except Room.DoesNotExist:
        pass
    return redirect('chat:admin_room')


@login_required
def admin_room(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)
    return render(request, 'chat/admin.html', {'rooms': rooms, 'users': users})


@login_required
def room_view(request, uuid):
    room = Room.objects.get(uuid=uuid)
    if room.status == Room.Status.WAITING:
        room.status = Room.Status.ACTIVE
        room.agent = request.user
        room.save()
    return render(request, 'chat/room.html', {"room": room})


@login_required
def add_user(request):
    form = AddUserForm()
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.is_staff = True
            user.save()
            return redirect('chat:admin_room')
    return render(request, 'chat/add_user.html', {'form': form})


@login_required
def user_view(request, uuid):
    user = User.objects.get(id=uuid)
    rooms = user.rooms.all()
    return render(request, 'chat/user.html', {"user": user, 'rooms': rooms})


main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')

chat/templates/chat/add_user.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-2xl mb-6">Add User</h1>
    <form method="post" class="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" class="inline-block mt-6 py-2 px-6 bg-rose-600 text-white rounded-xl">
    </form>
{% endblock %}

chat/templates/chat/admin.html
{% extends 'base.html' %}

{% block content %}
	<h1 class="text-2xl">Admin Chat</h1>
    <div class="mt-8">
        <h2 class="mb-4 text-lg">Users</h2>
        <a href="{% url 'chat:add_user' %}" class="inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Add User</a>

        <div class="mt-6">
            {% for user in users %}
            	<div class="grid grid-cols-4 gap-4 py-2 {% cycle 'bg-gray-100' 'bg-blue-100' %}">
                    <p class="px-2"><a href="{% url 'chat:user_detail' user.pk %}">{{ user.name }}</a></p>
                    <p class="px-2">{{ user.email }}</p>
                    <p class="px-2">{{ user.role }}</p>
                    <p class="px-2 text-right">
                        <a href="#" class="underline">Edit</a>
                    </p>
                </div>
            {% endfor %}
            
        </div>
    </div>
    <hr class="my-6">
    {% include 'chat/partials/rooms.html' %}
{% endblock %}

chat/templates/chat/partials/chat_bubble.html
<div id="chat" class="max-w-[300px] fixed right-2 bottom-2 p-4 bg-white border border-gray-300 rounded-xl">
    <div id="chat_icon">
        <button id="chat_open" class="w-[50px] flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                 stroke="currentColor" class="size-6 text-rose-600">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 0 1-.825-.242m9.345-8.334a2.126 2.126 0 0 0-.476-.095 48.64 48.64 0 0 0-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0 0 11.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155"/>
            </svg>
        </button>
    </div>
    <div id="chat_welcome" class="hidden">
        <input type="text" name="name" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100" placeholder="Your name">
        <button id="chat_join" class="py-2 px-6 rounded-xl text-white bg-rose-600">Join Chat</button>
    </div>
    <div id="chat_room" class="hidden">
        <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll">
            <p>Welcome to our chat! Please type your message and wait for an agent to join...</p>
        </div>
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Type your message">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Send</button>
    </div>
</div>

chat/templates/chat/partials/rooms.html
<div class="mt-8">
    <h2 class="mb-4 text-lg">Rooms</h2>
    <div class="grid grid-cols-4 gap-4">
        {% for room in rooms %}
            <div
                    class="p-4 rounded-xl
                        {% if room.status == 'WAITING' %}bg-emerald-100
                        {% elif room.status == 'ACTIVE' %}bg-yellow-100
                        {% else %}bg-gray-100
                        {% endif %}">
                <h3 class="mb-4 text-lg">Chat</h3>
                <p>
                    <b>ID: </b> {{ room.uuid }} <br>
                    <b>Name: </b> {{ room.client }} <br>
                    <b>Status: </b> {{ room.status }} <br>
                    <b>Agent: </b> {% firstof room.agent.name 'None yet...' %}
                </p>
                <a href="{% url 'chat:room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-emerald-800 text-white rounded-xl">Join</a>
                <a href="{% url 'chat:delete_room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-rose-800 text-white rounded-xl">Delete</a>
            </div>
        {% endfor %}
    </div>
</div>

chat/templates/chat/room.html
{% extends 'base.html' %}
{% load tags %}
{% load static %}

{% block content %}
    <h1 class="text-2xl">Room "{{ room.uuid }}"</h1>

    <hr class="my-6">

    <p class="mb-6">
        <b>Name: </b>{{ room.client }}<br>
        <b>Started: </b>{{ room.created_at|timesince }} ago<br>
        <b>Status: </b>{{ room.get_status_display }}<br>
        <b>Page: </b>{{ room.url }}<br>
        <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
    </p>

    <hr class="mb-6">

    <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
        {% for message in room.messages.all %}
            <div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}">
                {% if not message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}

                <div>
                    <div class="p-4 rounded-xl {% if message.created_by %}bg-blue-600 text-white{% else %}bg-gray-300{% endif %}">
                        <p class="text-sm">{{ message.body }}</p>
                    </div>

                    <span class="text-xs text-gray-500 leading-none">{{ message.created_at|timesince }} ago</span>
                </div>

                {% if message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    {% if room.status == 'ACTIVE' %}
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl"
               placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Send</button>
    {% endif %}
{% endblock %}

{% block scripts %}
	{% if room.status == 'ACTIVE' %}
        {{ room.uuid | json_script:'room_uuid' }}
        {{ request.user.name | json_script:'user_name' }}
        {{ request.user.id | json_script:'user_id' }}
        <script src="{% static 'js/main_admin.js' %}"></script>
	{% endif %}
{% endblock %}

chat/templates/chat/user.html
{% extends 'base.html' %}


{% block content %}
	<h1 class="text-2xl mb-6">User Detail</h1>
    {{ user.name }}
    <hr class="my-6">
    {% include 'chat/partials/rooms.html' %}
{% endblock %}

main/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-6 text-2xl">About</h1>
{% endblock %}

main/templates/base.html
{% load static %}

<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    </head>

    <body>
        <div class="p-2">
            <nav class="p-6 bg-rose-600 text-white flex justify-between items-center rounded-xl">
                <a href="{% url 'main:index' %}" class="text-xl">LiveChat</a>

                <div class="flex items-center space-x-4">
                    <a href="{% url 'main:index' %}">Home</a>
                    <a href="{% url 'main:about' %}">About</a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'chat:admin_room' %}" class="inline-block py-4 px-6 bg-rose-800 text-white rounded-xl">Admin</a>
                    {% endif %}
                </div>
            </nav>

            <main class="max-w-6xl mx-auto p-6">
                {% if messages %}
                    <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                {% block content %}
                {% endblock %}
            </main>
        </div>

        <footer class="py-12 px-6 bg-gray-800 text-white text-center text-xs">
            <p>Copyright (c) 2023 - LiveChat</p>
        </footer>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

main/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="mt-12 py-12 px-8 grid grid-cols-5 gap-4 items-center border border-rose-200 rounded-xl">
        <div class="col-span-2">
            <img src="{% static 'images/header.png' %}">
        </div>

        <div class="col-span-3">
            <h1 class="mb-8 text-3xl">Welcome to LiveChat</h1>

            <h2 class="text-lg text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor. Suspendisse vitae augue dolor. Nunc sed eleifend nulla.</h2>
        </div>
    </div>

    <div class="mt-12 py-12 px-8 grid grid-cols-3 gap-4 items-center">
        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>
    </div>
    {% include 'chat/partials/chat_bubble.html' %}
{% endblock %}
{% block scripts %}
    {% csrf_token %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}